CREATE TABLE TIPOFILMES(
    CHAVE INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100)
);

CREATE TABLE FILMES( 
    CHAVE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(1000) NOT NULL, TIPO INT, 
    INDICACAO VARCHAR(1000), 
    QUANTIDADEVOTOS INT DEFAULT 0, 
    FOREIGN KEY (TIPO) REFERENCES TIPOFILMES(CHAVE) );

INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (1, 'Ação');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (2, 'Aventura');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (3, 'Cinema de arte');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (4, 'Chanchada');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (5, 'Comédia');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (6, 'Comédia de ação');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (7, 'Comédia de terror');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (8, 'Comédia dramática');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (9, 'Comédia romântica');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (10, 'Dança');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (11, 'Documentário');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (12, 'Docuficção');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (13, 'Drama');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (14, 'Espionagem');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (15, 'Faroeste');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (16, 'Fantasia');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (17, 'Fantasia científica');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (18, 'Ficção científica');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (19, 'Filmes com truques');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (20, 'Filmes de guerra');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (21, 'Musical');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (22, 'Filme policial');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (23, 'Romance');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (24, 'Seriado');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (25, 'Suspense');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (26, 'Terror');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (27, 'Thriller');
INSERT INTO TIPOFILMES(CHAVE, DESCRICAO) VALUES (28, 'Pornográfico');


INSERT INTO FILMES (NOME, TIPO, INDICACAO, QUANTIDADEVOTOS) VALUES ('GUERRA INFINITA', 1, 'Rodrigo', 1);
INSERT INTO FILMES (NOME, TIPO, INDICACAO, QUANTIDADEVOTOS) VALUES ('VINGADORES', 1, 'Rodrigo', 1);
